device-info:
    deviceId: 3
    deviceType: 'ODROID'
    mac-address: '00:1e:06:10:2d:70'
rabbit-mq:
    username: 'guest'
    password: 'guest'
    send-queue: 'sendQueue'
    syslog-queue: 'syslogQueue'
message-service:
    uri: 'http://scottf.ddns.net/SpeedService/'
    post-svc: 'postResult.json'

request-service:
    uri: 'http://scottf.ddns.net/SpeedService/'
    get-config-svc: 'getSessionConfiguration.json'
    update-status-svc: 'updateStatus.json'
general:
    ping-timeout: 60 #seconds
    remote-timeout: 60 #seconds 
    request-config-timeout: 60 #seconds
    update-request-status-timeout: 60 #seconds
    sleep-on-boot: 30
    path: '/opt/SpeedDevice/'
speed-test:
    mini-enabled: false
    mini-server: 'http://192.168.56.222/mini/'
    simple-enabled: false
    share-enabled: true
